name: flutter_sales_graph_example
description: Example app for flutter_sales_graph.
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sales_graph:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
